import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import { useSelector, useDispatch } from "react-redux";
import { decrement, increment } from "../src/store/counterSlice";
import { getKanyeQuote, selectKanye } from "../src/store/kanyeSlice";

export default function About() {
  const count = useSelector((state) => state.counter.value);
  const { data, pending, error } = useSelector(selectKanye);
  const dispatch = useDispatch();

  return (
    <div className={styles.container}>
      <Head>
        <title>Store Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Store page</h1>

        <Link href="/">
          <a>go to home</a>
        </Link>

        <div>
          <h2>counter store sync</h2>
          <div>{count}</div>
        <button onClick={() => dispatch(increment())}>+</button>
        <button onClick={() => dispatch(decrement())}>-</button>
        </div>

        <div>
          <h2>Kanye West quote store with async thunk</h2>
          {pending && <p>Loading...</p>}
          {data && <p>{data.quote}</p>}
          {error && <p>Oops, something went wrong</p>}
          <button onClick={() => dispatch(getKanyeQuote())} disabled={pending}>
            Generate Kanye Quote
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
